baseURL = "https://ikbelgoedkoop.nl"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
themesDir = "../.."
title = "IkBelGoedkoop"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
name = "over ons"
pre = "#"
url = "about"
weight = 1
[[Languages.en.menu.main]]
name = "services"
pre = "#"
url = "services"
weight = 2
[[Languages.en.menu.main]]
name = "team"
pre = "#"
url = "team"
weight = 3
[[Languages.en.menu.main]]
name = "pricing"
pre = "#"
url = "pricing"
weight = 4
[[Languages.en.menu.main]]
name = "blog"
pre = "#"
url = "blog"
weight = 5
[[Languages.en.menu.main]]
name = "contact"
pre = "#"
url = "contact"
weight = 6
[[Languages.en.menu.main]]
name = "Sign in"
pre = ""
url = "https://dial.cheap/"
weight = 7
[params]
author = "ikbelgoedkoop"
description = "ikbelgoedkoop. Overal bereikbaar en makkelijk te integreren met uw zakelijke vaste en mobiele nummers"
google_analytics_id = "256941958"
logo = "images/logo.png"
post_share = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDaiU9z6hw1O_4V7VVkfuEOBt99X8tvNPw"
map_latitude = "12.12774"
map_longitude = "-68.90764"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/logo.png"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/dialcheap"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://www.twitter.com/dial_cheap"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/tjapko-smits-2388aa202"
